### ISSUE TITLE
CSS 기본 설명

### ISSUE THREAD

**Issue by JoonKL** [JoonKL/Study_make-M.B.T.I-page#2]
# 초기 설정

css rest 단어로 검색을 하면 
https://meyerweb.com/eric/tools/css/reset/
링크와 같은 css reset code를 가져올 수 있다

```css
/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
```
css reset 코드는 html에 기본적으로 있는 style을 초기화 시켜주는 코드이다.
높이, 여백, 글꼴 크기 등 브라우저 마다 다른 값을 통일 시켜주고 사용자가 원하는대로 커스터마이징을 하는데 있어서 편리하게 해준다.

```html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>타이틀</title>
    <link rel="stylesheet" type="text/css" href="css/reset.css">
    <link rel="stylesheet" type="text/css" href="css/form.css">
</head>
```

## HTML에서 CSS 파일 연동
위와 같이 html 파일의 <head> 안에 <link>라는 태그를 사용하여 css 파일을 연동하여 사용할 수 있도록```<link>```를 설정할 수 있다.

``` <link rel="stylesheet" type="text/css" href="css/reset.css"> ```
css reset 코드를 불러와서 html 스타일을 초기화 시켜주는 코드
``` <link rel="stylesheet" type="text/css" href="css/form.css">```
form.css 라는 개인이 커스터 마이징한 html 스타일을 불러오는 코드
