### ISSUE TITLE
CSS 기본적인 구조

### ISSUE THREAD

**Issue by JoonKL** [JoonKL/Study_make-M.B.T.I-page#3]
# 폰트 사용
폰트를 다운로드 받아서 사용할 수도 있지만, 웹 폰트를 사용하는 방법을 사용.

 ```css
@font-face {
    font-family: 'GmarketSansBold';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansBold.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
```
눈누 라는 사이트에서 다양한 웹폰트 코드를 사용 가능

css 코드를 작성하는데 있어선
html의 구조에서 사용했던 태그를 불러와서 해당 태그를 꾸민다고 생각하면 편함

### 예제1

```css
body{
    width: 100%;  폭 지정
    height: 100%;  높이 지정
    background-color: #FAF1BE; 해당 태그의 배경화면 색
    color: #000;  해당 태그의 색
    font-family: "NEXON Lv1 Gothic OTF"; 해당 태그의 폰트
}
```
위 코드는 html의 태그 중 ```<body>``` 태그를 가져와서 해당 태그의 스타일을 지정

### 예제2
```css
.result_data h3{
    text-align: center;  글자 정렬 지정
    font-size: 20px;  글자 크기(단위:px)
    font-weight: bold;  글자 형태(굵기)
    padding: 20px 0 30px;  태그의 안쪽 여백(0시 3시 6시 9시 여백을 표시) 
    /*padding-top: 5px 
    padding-bottom: 10px 과 같은 형태로 지정을 해주기도함*/
}
```

## 속성 정리
```css



}
